package com.luthfihariz.almasgocore.controller.dto;

public enum ErrorCode {
    ERROR_INTERNAL_SERVER,
    ERROR_USER_ALREADY_REGISTERED,
    ERROR_USER_NOT_FOUND,
    ERROR_CONTENT_NOT_FOUND,
    ERROR_ADD_CONTENT_FAILURE,
    ERROR_WRONG_CREDENTIAL,
    ERROR_INVALID_OLD_PASSWORD,
    ERROR_ENGINE_NOT_FOUND,
    ERROR_SEND_EMAIL_FAILURE,
    ERROR_EMAIL_NOT_FOUND
}
